<div align="center"> 
    
# ***Manufacturing Downtime Optimization***
##### Data-Driven Manufacturing Performance, Downtime & Predictive Analytics

 </div>

--- 

## 🔍 Project Overview
##### This project focuses on analyzing manufacturing downtime, production performance, product quality, energy consumption, and machine operating conditions to identify operational inefficiencies and factors associated with machine failures.

##### It aims to the major causes of downtime, evaluate machine and shift productivity, monitor production quality and energy efficiency, and develop data-driven insights and predictive models to support downtime reduction and improve overall manufacturing performance.

##### The project is designed for manufacturing operations managers, production engineers, quality control teams, and maintenance teams seeking to improve equipment utilization, reduce production losses, enhance product quality, and make informed operational decisions through data analytics and predictive maintenance .


---

## 🛠️ Technology Stack 

| **Category** | **Technology** |
|:---------|:-----------|
| ***Programming Language*** | *Python* |
| ***Data Manipulation*** | *Pandas* , *Numpy* |
| ***Data Visualization*** | *Matplotlib, Seaborn , Power BI*  |
| ***Database Language*** | *SQL* |
| ***Database Management System*** | *SQL Server* |
| ***Database Design*** | *Star Schema* |
| ***Data Source*** | *manufacturing Dataset* |

---

<div style="color: Orange; text-align: center; padding: 7px; border-radius: 5px; font-weight: bold; font-size: 25px;">Analysis Implementation 
</div>

### **1- Import Libraries**
##### Import the required Python libraries for data manipulation, visualization, and analysis.

In [589]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

### **2- Data Acquisition**
##### Load the manufacturing.csv dataset as the source data for the analysis .

In [590]:
try :
    Source_File = 'smart_factory_comprehensive.xlsx'
    Sheet_Name = 'smart_factory_comprehensive'
    smart_factory = pd.read_excel(Source_File , sheet_name = Sheet_Name )
except FileNotFoundError :
    print("File missing")
else :
    print("File loaded successfully")
finally :
    print("Execution finished")

File loaded successfully
Execution finished

### **3- Dataset Inspection**
#### Inspect the structure, dimensions, data types, and overall quality of the datasets.
---

In [591]:
# Preview the first 5 records to understand the dataset structure.
smart_factory.head()

,date,shift,machine_id,operator_id,product_id,planned_time_min,downtime_min,downtime_reason,total_units,good_units,reject_units,defect_type,energy_kwh,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure
0,2025-01-01,Shift_1,M01,OP018,P_D,480,0,No Downtime,585,552,33,Scratch,50.99,H,299.7,309.2,1456,40.6,182,0
1,2025-01-01,Shift_1,M02,OP012,P_B,480,30,Setup,683,647,36,Dimension Error,61.27,H,297.7,309.7,1440,51.1,191,0
2,2025-01-01,Shift_1,M03,OP029,P_B,480,39,Setup,650,616,34,Surface Defect,40.69,L,300.3,311.7,1707,33.6,158,0
3,2025-01-01,Shift_1,M04,OP031,P_B,480,170,Breakdown,467,394,73,Scratch,41.49,H,300.5,309.9,1397,45.9,210,1
4,2025-01-01,Shift_1,M05,OP033,P_E,480,0,No Downtime,740,712,28,Dimension Error,42.45,M,297.4,308.3,1535,34.6,51,0

In [592]:
# Preview the last 5 records to verify the dataset ends correctly.
smart_factory.tail()

,date,shift,machine_id,operator_id,product_id,planned_time_min,downtime_min,downtime_reason,total_units,good_units,reject_units,defect_type,energy_kwh,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure
10025,2025-06-25,Shift_3,M16,OP021,P_C,480,0,No Downtime,657,639,18,Scratch,45.60,L,300.8,312.1,1512,37.1,169,0
10026,2025-06-26,Shift_1,M16,OP035,P_A,480,0,No Downtime,576,567,9,Crack,59.35,L,296.7,307.8,1453,46.0,33,0
10027,2025-06-26,Shift_2,M16,OP018,P_B,480,0,No Downtime,738,699,39,Crack,54.66,L,301.5,310.7,1466,43.6,56,0
10028,2025-06-26,Shift_3,M16,OP021,P_A,480,33,Maintenance,605,595,10,Dimension Error,39.08,M,300.7,311.2,1769,26.5,63,0
10029,2025-06-27,Shift_1,M16,OP033,P_B,480,0,No Downtime,588,567,21,Surface Defect,52.33,L,302.6,310.3,1479,40.4,105,0

In [593]:
# Check the number of rows and columns in the dataset.
smart_factory.shape

(10030, 20)

In [594]:
smart_factory.dtypes

date                       datetime64[ns]
shift                              object
machine_id                         object
operator_id                        object
product_id                         object
planned_time_min                    int64
downtime_min                        int64
downtime_reason                    object
total_units                         int64
good_units                          int64
reject_units                        int64
defect_type                        object
energy_kwh                        float64
Type                               object
Air temperature [K]               float64
Process temperature [K]           float64
Rotational speed [rpm]              int64
Torque [Nm]                       float64
Tool wear [min]                     int64
Machine failure                     int64
dtype: object

In [595]:
# Inspect data types and non-null values for each column.
smart_factory.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10030 entries, 0 to 10029
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   date                     10030 non-null  datetime64[ns]
 1   shift                    10030 non-null  object
 2   machine_id               10030 non-null  object
 3   operator_id              10030 non-null  object
 4   product_id               10030 non-null  object
 5   planned_time_min         10030 non-null  int64
 6   downtime_min             10030 non-null  int64
 7   downtime_reason          10030 non-null  object
 8   total_units              10030 non-null  int64
 9   good_units               10030 non-null  int64
 10  reject_units             10030 non-null  int64
 11  defect_type              10030 non-null  object
 12  energy_kwh               9915 non-null   float64
 13  Type                     10030 non-null  object
 14  Air temperature [K]      10030 non-null  float64
 15  Process temperature [K]  10030 non-null  float64
 16  Rotational speed [rpm]   10030 non-null  int64
 17  Torque [Nm]              10030 non-null  float64
 18  Tool wear [min]          10030 non-null  int64
 19  Machine failure          10030 non-null  int64
dtypes: datetime64[ns](1), float64(4), int64(8), object(7)
memory usage: 1.5+ MB

#### `Observation`
- The dataset contains 10030 records and 20 features, providing sufficient data for business analysis.
- The dataset includes numerical, categorical, and datetime features.
- Data quality is generally good, with 9,915 out of 10,030 records (98.85%) containing non-missing energy_kwh values, while 115 records (1.15%) have missing values in this column.

In [596]:
# Display all column names for inspection . 
smart_factory.columns

Index(['date', 'shift', 'machine_id', 'operator_id', 'product_id',
       'planned_time_min', 'downtime_min', 'downtime_reason', 'total_units',
       'good_units', 'reject_units', 'defect_type', 'energy_kwh', 'Type',
       'Air temperature [K]', 'Process temperature [K]',
       'Rotational speed [rpm]', 'Torque [Nm]', 'Tool wear [min]',
       'Machine failure'],
      dtype='object')

In [597]:
# Generate summary statistics for numerical features.
smart_factory.describe()

,date,planned_time_min,downtime_min,total_units,good_units,reject_units,energy_kwh,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure
count,10030,10030.0,10030.000000,10030.000000,10030.000000,10030.000000,9915.000000,10030.000000,10030.000000,10030.000000,10030.000000,10030.000000,10030.000000
mean,2025-03-25 01:18:49.172482560,480.0,16.000897,693.808574,668.042871,25.765703,48.767727,300.005503,310.006122,1538.841276,40.092871,107.950449,0.033799
min,2025-01-01 00:00:00,480.0,0.000000,391.000000,317.000000,5.000000,8.900000,295.300000,305.700000,1168.000000,3.800000,0.000000,0.000000
25%,2025-02-11 00:00:00,480.0,0.000000,650.000000,626.000000,15.000000,42.970000,298.300000,308.800000,1423.000000,33.200000,53.000000,0.000000
50%,2025-03-25 00:00:00,480.0,0.000000,695.500000,672.000000,24.000000,48.650000,300.100000,310.100000,1503.000000,40.100000,108.000000,0.000000
75%,2025-05-05 18:00:00,480.0,29.000000,741.000000,715.750000,33.000000,54.430000,301.500000,311.100000,1612.000000,46.800000,162.000000,0.000000
max,2025-06-27 00:00:00,480.0,180.000000,864.000000,854.000000,153.000000,82.020000,304.500000,313.800000,2886.000000,152.250000,253.000000,1.000000
std,NaN,0.0,26.265165,70.169116,72.417416,14.704994,8.598021,2.000136,1.483802,179.224899,10.389660,63.671456,0.180719

#### `Observation`
- The dataset contains **10,030 records**, each with a planned operating time of 480 minutes.
- Average downtime is **25.77 minutes**, while average actual operating time is **454.23 minutes** per record.
- Average production is **693.81 units**, and energy consumption averages **25.77 kWh**.
- Average air and process temperatures are **300.01 K** and **310.01 K**, respectively.
- Machine failure occurs in **3.38% of records**, indicating an imbalanced target variable.

In [598]:
# Generate summary statistics for categorical features.
smart_factory.describe(include=['object','string'])

,shift,machine_id,operator_id,product_id,downtime_reason,defect_type,Type
count,10030,10030,10030,10030,10030,10030,10030
unique,3,20,40,5,6,4,3
top,Shift_1,M16,OP029,P_D,No Downtime,Scratch,L
freq,3352,534,281,2026,5978,2534,6019

#### `Observation`
- The dataset contains **10,030 records** across 3 shifts, 20 machines, and 40 operators.
- **Shift_1** is the most frequent shift, with 3,352 records.
- There are 5 downtime reasons, with **P_D** being the most frequent (2,026 records).
- **No Downtime** is the most common defect_type entry, appearing in 5,978 records.
- The most frequent product type is **Type L**, with 6,019 records.

<div style="color: Green;  padding: 7px; border-radius: 5px; font-weight: bold; font-size: 25px;"> Data Cleaning </div>

---

In [599]:
# Display Columns with Missing Values (> 0%)
missing_percentage = (smart_factory.isnull().mean().mul(100).round(2).sort_values(ascending=False))
missing_percentage = missing_percentage[missing_percentage > 0]
print(missing_percentage)

energy_kwh    1.15
dtype: float64

#### `Observation`
-  The missing values represent  1.15% of the dataset , So the smart_factory dataset has contain missing values in column energy_kwh  .

In [600]:
# Handling missing values 
smart_factory['energy_kwh'] = smart_factory['energy_kwh'].fillna(smart_factory['energy_kwh'].median())

In [601]:
# Checking for missing values after cleaned it
smart_factory.isnull().sum()

date                       0
shift                      0
machine_id                 0
operator_id                0
product_id                 0
planned_time_min           0
downtime_min               0
downtime_reason            0
total_units                0
good_units                 0
reject_units               0
defect_type                0
energy_kwh                 0
Type                       0
Air temperature [K]        0
Process temperature [K]    0
Rotational speed [rpm]     0
Torque [Nm]                0
Tool wear [min]            0
Machine failure            0
dtype: int64

In [602]:
# Identify duplicate records in the dataset.
print("duplicates =",smart_factory.duplicated().sum())

duplicates = 30

In [603]:
# Display duplicate records in the dataset.
smart_factory[smart_factory.duplicated()]

,date,shift,machine_id,operator_id,product_id,planned_time_min,downtime_min,downtime_reason,total_units,good_units,reject_units,defect_type,energy_kwh,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure
509,2025-01-09,Shift_2,M09,OP012,P_C,480,52,Unspecified,553,545,8,Crack,41.37,M,300.8,310.3,1526,36.3,205,0
606,2025-01-11,Shift_1,M05,OP027,P_D,480,0,No Downtime,751,740,11,Crack,58.53,L,298.4,309.4,1385,50.0,201,0
751,2025-01-13,Shift_2,M09,OP032,P_D,480,0,No Downtime,842,797,45,Scratch,53.18,L,300.1,311.3,1535,42.3,92,0
1868,2025-02-01,Shift_1,M05,OP025,P_B,480,0,No Downtime,720,683,37,Crack,33.10,L,303.0,311.1,1980,20.2,137,0
1965,2025-02-02,Shift_3,M01,OP015,P_D,480,0,No Downtime,731,695,36,Dimension Error,52.44,L,301.5,310.5,1556,39.1,48,0
2388,2025-02-09,Shift_3,M03,OP029,P_E,480,37,Material Shortage,634,612,22,Scratch,58.14,L,300.2,311.6,1375,56.9,155,0
2937,2025-02-18,Shift_3,M11,OP010,P_C,480,0,No Downtime,664,639,25,Dimension Error,56.35,L,300.5,309.7,1580,42.8,196,0
4232,2025-03-12,Shift_2,M05,OP015,P_C,480,0,No Downtime,783,743,40,Surface Defect,56.59,L,303.4,311.8,1499,45.0,16,0
4289,2025-03-13,Shift_2,M01,OP003,P_D,480,0,No Downtime,747,715,32,Scratch,51.94,L,297.8,307.4,1355,45.8,60,0
4450,2025-03-16,Shift_1,M01,OP017,P_B,480,0,No Downtime,684,671,13,Scratch,40.26,L,298.9,310.5,1717,26.9,17,0
4458,2025-03-16,Shift_1,M08,OP020,P_D,480,0,No Downtime,754,744,10,Crack,52.75,M,304.2,313.8,1481,44.9,136,0
4589,2025-03-18,Shift_1,M18,OP015,P_D,480,0,No Downtime,735,704,31,Dimension Error,60.59,L,299.7,309.0,1412,49.2,85,0
5009,2025-03-25,Shift_1,M17,OP003,P_D,480,51,Setup,650,619,31,Surface Defect,37.71,H,298.0,307.6,1593,32.2,118,0
5637,2025-04-04,Shift_3,M04,OP034,P_B,480,0,No Downtime,685,664,21,Surface Defect,43.72,L,298.5,309.6,1724,26.4,100,0
5730,2025-04-06,Shift_1,M16,OP030,P_B,480,0,No Downtime,695,679,16,Dimension Error,64.69,L,298.9,309.8,1411,56.3,84,0
5914,2025-04-09,Shift_1,M19,OP022,P_E,480,0,No Downtime,780,740,40,Dimension Error,37.45,L,302.7,310.6,1686,26.3,9,0
5977,2025-04-10,Shift_2,M01,OP013,P_D,480,39,Material Shortage,575,546,29,Dimension Error,37.96,M,298.9,308.4,1827,26.1,5,0
6006,2025-04-10,Shift_3,M09,OP037,P_D,480,0,No Downtime,686,649,37,Dimension Error,36.24,H,297.5,308.4,1793,23.9,28,0
6239,2025-04-14,Shift_3,M01,OP018,P_C,480,0,No Downtime,722,682,40,Surface Defect,63.31,H,299.1,308.8,1566,46.6,192,0
6608,2025-04-20,Shift_3,M09,OP012,P_C,480,0,No Downtime,709,690,19,Surface Defect,41.81,L,299.9,309.8,1716,28.2,117,0
6776,2025-04-23,Shift_2,M16,OP039,P_E,480,0,No Downtime,636,629,7,Surface Defect,67.82,L,299.3,310.5,1281,59.8,15,0
7018,2025-04-27,Shift_2,M17,OP026,P_D,480,0,No Downtime,823,779,44,Surface Defect,49.74,L,299.2,308.9,1526,37.9,177,0
7609,2025-05-07,Shift_2,M07,OP013,P_B,480,0,No Downtime,794,764,30,Surface Defect,59.63,L,304.2,313.3,1410,51.6,47,0
8614,2025-05-24,Shift_1,M11,OP032,P_A,480,0,No Downtime,730,705,25,Crack,47.05,M,303.8,312.4,1597,33.4,203,0
8808,2025-05-27,Shift_2,M04,OP038,P_E,480,0,No Downtime,792,756,36,Surface Defect,56.11,L,297.3,309.0,1548,37.4,171,0
9202,2025-06-03,Shift_1,M12,OP023,P_A,480,0,No Downtime,743,723,20,Dimension Error,48.40,M,300.2,310.2,1429,43.8,54,0
9356,2025-06-06,Shift_1,M04,OP022,P_C,480,0,No Downtime,725,688,37,Scratch,52.58,M,299.0,310.3,1558,35.4,223,0
9440,2025-06-07,Shift_3,M06,OP039,P_B,480,0,No Downtime,716,699,17,Surface Defect,61.98,H,300.5,310.0,1495,47.4,184,0
9584,2025-06-10,Shift_3,M15,OP038,P_B,480,0,No Downtime,836,799,37,Dimension Error,60.04,L,299.9,309.8,1477,47.7,112,0
9672,2025-06-12,Shift_3,M15,OP030,P_A,480,0,No Downtime,804,774,30,Surface Defect,42.64,M,300.5,312.0,1779,27.7,46,0

#### `Observation`
- the smart_factory dataset has contain 30 duplicated values

In [604]:
# drop_duplicates
smart_factory = smart_factory.drop_duplicates()

In [605]:
# Checking after drop_duplicates 
print("duplicates =",smart_factory.duplicated().sum())

duplicates = 0

In [606]:
# Count the number of unique values in each column.
smart_factory.nunique()

date                        178
shift                         3
machine_id                   20
operator_id                  40
product_id                    5
planned_time_min              1
downtime_min                164
downtime_reason               6
total_units                 411
good_units                  461
reject_units                126
defect_type                   4
energy_kwh                 3351
Type                          3
Air temperature [K]          93
Process temperature [K]      82
Rotational speed [rpm]      941
Torque [Nm]                 593
Tool wear [min]             246
Machine failure               2
dtype: int64

In [607]:
# Standardize column names by:Removing leading/trailing whitespace,Converting names to Title ,Replacing spaces and hyphens with underscores.
# snake_case 
smart_factory.columns = (smart_factory.columns.str.strip().str.replace(" " ,"_" , regex = False).str.replace("/" ,"_" , regex = False)
    .str.replace("-" ,"_" , regex = False).str.lower()) 
print(smart_factory.columns)

Index(['date', 'shift', 'machine_id', 'operator_id', 'product_id',
       'planned_time_min', 'downtime_min', 'downtime_reason', 'total_units',
       'good_units', 'reject_units', 'defect_type', 'energy_kwh', 'type',
       'air_temperature_[k]', 'process_temperature_[k]',
       'rotational_speed_[rpm]', 'torque_[nm]', 'tool_wear_[min]',
       'machine_failure'],
      dtype='object')

In [608]:
# Mapped product type codes to descriptive quality levels: High, Medium, and Low.
smart_factory['shift_name'] = smart_factory['shift'].replace({'Shift_1':'Morning','Shift_2':'Evening','Shift_3':'Night'})

In [609]:
# Mapped product type codes to descriptive quality levels: High, Medium, and Low.
smart_factory['product_quality'] = smart_factory['type'].replace({'H':'High' ,'L': 'Low' ,'M': 'Medium'})

In [610]:
# Identified inconsistencies between downtime duration and downtime reason.
count = len(smart_factory[(smart_factory['downtime_min'] == 0) & (smart_factory['downtime_reason'] != 'No Downtime')])
print('Zero downtime with a specified reason =' ,count)
count1 = len(smart_factory[(smart_factory['downtime_min'] != 0) & (smart_factory['downtime_reason'] == 'No Downtime')])
print('Non-zero downtime with no downtime reason =',count1)
count2 = len(smart_factory[(smart_factory['downtime_min'] != 0) & (smart_factory['downtime_reason'] != 'No Downtime')])
print('Non-zero downtime with a specified reason =',count2)

Zero downtime with a specified reason = 0
Non-zero downtime with no downtime reason = 103
Non-zero downtime with a specified reason = 4048

In [611]:
# Replace unspecified downtime reasons for records with non-zero downtime
smart_factory.loc[(smart_factory['downtime_min'] != 0) &(smart_factory['downtime_reason'] == 'No Downtime'),
    'downtime_reason'] = 'Unspecified'

In [612]:
# Check for remaining inconsistent records between downtime duration and downtime reason.
count = len(smart_factory[(smart_factory['downtime_min'] == 0) & (smart_factory['downtime_reason'] != 'No Downtime')])
print('Zero downtime with a specified reason =' ,count)
count1 = len(smart_factory[(smart_factory['downtime_min'] != 0) & (smart_factory['downtime_reason'] == 'No Downtime')])
print('Non-zero downtime with no downtime reason =',count1)
count2 = len(smart_factory[(smart_factory['downtime_min'] != 0) & (smart_factory['downtime_reason'] != 'No Downtime')])
print('Non-zero downtime with a specified reason =',count2)

Zero downtime with a specified reason = 0
Non-zero downtime with no downtime reason = 0
Non-zero downtime with a specified reason = 4151

In [613]:
smart_factory['downtime_reason'].unique()

array(['No Downtime', 'Setup', 'Breakdown', 'Unspecified', 'Maintenance',
       'Material Shortage'], dtype=object)

<div style="color: LightBlue;  padding: 7px; border-radius: 5px; font-weight: bold; font-size: 35px;"> Data Warehouse Design </div>
<div style="color: LightBlue;  padding: 7px; border-radius: 5px; font-weight: bold; font-size: 20px;"> Grain : One row per machine, per shift, per day </div>

### Building Dimension & Fact Tables

#### 1- Dim_Date

In [614]:
smart_factory.columns = (
    smart_factory.columns.str.replace(" ", "_", regex=False)
    .str.replace("-", "_", regex=False)
    .str.replace("[", "", regex=False)
    .str.replace("]", "", regex=False)
    .str.lower()
)
smart_factory.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 0 to 10029
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   date                   10000 non-null  datetime64[ns]
 1   shift                  10000 non-null  object
 2   machine_id             10000 non-null  object
 3   operator_id            10000 non-null  object
 4   product_id             10000 non-null  object
 5   planned_time_min       10000 non-null  int64
 6   downtime_min           10000 non-null  int64
 7   downtime_reason        10000 non-null  object
 8   total_units            10000 non-null  int64
 9   good_units             10000 non-null  int64
 10  reject_units           10000 non-null  int64
 11  defect_type            10000 non-null  object
 12  energy_kwh             10000 non-null  float64
 13  type                   10000 non-null  object
 14  air_temperature_k      10000 non-null  float64
 15  process_temperature_k  10000 non-null  float64
 16  rotational_speed_rpm   10000 non-null  int64
 17  torque_nm              10000 non-null  float64
 18  tool_wear_min          10000 non-null  int64
 19  machine_failure        10000 non-null  int64
 20  shift_name             10000 non-null  object
 21  product_quality        10000 non-null  object
dtypes: datetime64[ns](1), float64(4), int64(8), object(9)
memory usage: 1.8+ MB

In [615]:
dates = smart_factory['date'].drop_duplicates().sort_values()
print(dates)

0       2025-01-01
60      2025-01-02
120     2025-01-03
180     2025-01-04
240     2025-01-05
           ...
10011   2025-06-23
10019   2025-06-24
10023   2025-06-25
10026   2025-06-26
10029   2025-06-27
Name: date, Length: 178, dtype: datetime64[ns]

In [616]:
dim_date = pd.DataFrame({"full_date" : dates})
dim_date["date_key"] = dim_date["full_date"].dt.strftime("%Y%m%d").astype(int)
dim_date["year"] = dim_date["full_date"].dt.year
dim_date["quarter"] = dim_date["full_date"].dt.quarter
dim_date["month_name"] = dim_date["full_date"].dt.month_name()
dim_date["month"] = dim_date["full_date"].dt.month
dim_date["day"] = dim_date["full_date"].dt.day
dim_date["day_of_year"] = dim_date["full_date"].dt.dayofyear
dim_date["day_name"] = dim_date["full_date"].dt.day_name()
dim_date["week_of_year"] = dim_date["full_date"].dt.isocalendar().week.astype(int)
dim_date["is_weekend"] = dim_date["full_date"].dt.dayofweek >= 5
dim_date = dim_date[["date_key","full_date","year","quarter","month_name","month","day_name","day","day_of_year","week_of_year","is_weekend"]].reset_index(drop=True)
dim_date

,date_key,full_date,year,quarter,month_name,month,day_name,day,day_of_year,week_of_year,is_weekend
0,20250101,2025-01-01,2025,1,January,1,Wednesday,1,1,1,False
1,20250102,2025-01-02,2025,1,January,1,Thursday,2,2,1,False
2,20250103,2025-01-03,2025,1,January,1,Friday,3,3,1,False
3,20250104,2025-01-04,2025,1,January,1,Saturday,4,4,1,True
4,20250105,2025-01-05,2025,1,January,1,Sunday,5,5,1,True
...,...,...,...,...,...,...,...,...,...,...,...
173,20250623,2025-06-23,2025,2,June,6,Monday,23,174,26,False
174,20250624,2025-06-24,2025,2,June,6,Tuesday,24,175,26,False
175,20250625,2025-06-25,2025,2,June,6,Wednesday,25,176,26,False
176,20250626,2025-06-26,2025,2,June,6,Thursday,26,177,26,False
177,20250627,2025-06-27,2025,2,June,6,Friday,27,178,26,False

#### 2- Dim_Shift

In [617]:
dim_shift = smart_factory[["shift","shift_name"]].drop_duplicates().sort_values("shift").reset_index(drop=True)
dim_shift.insert(0, "shift_key", dim_shift.index + 1)
dim_shift

   shift_key    shift shift_name
0          1  Shift_1    Morning
1          2  Shift_2    Evening
2          3  Shift_3      Night

#### 3- Dim_Machine

In [618]:
dim_machine = smart_factory[["machine_id"]].drop_duplicates().sort_values("machine_id").reset_index(drop=True)
dim_machine.insert(0, "machine_key", dim_machine.index + 1)
dim_machine

    machine_key machine_id
0             1        M01
1             2        M02
2             3        M03
3             4        M04
4             5        M05
5             6        M06
6             7        M07
7             8        M08
8             9        M09
9            10        M10
10           11        M11
11           12        M12
12           13        M13
13           14        M14
14           15        M15
15           16        M16
16           17        M17
17           18        M18
18           19        M19
19           20        M20

#### 4- Dim_Operator

In [619]:
dim_operator = smart_factory[["operator_id"]].drop_duplicates().sort_values("operator_id").reset_index(drop=True)
dim_operator.insert(0, "operator_key", dim_operator.index + 1)
dim_operator

    operator_key operator_id
0              1       OP001
1              2       OP002
2              3       OP003
3              4       OP004
4              5       OP005
5              6       OP006
6              7       OP007
7              8       OP008
8              9       OP009
9             10       OP010
10            11       OP011
11            12       OP012
12            13       OP013
13            14       OP014
14            15       OP015
15            16       OP016
16            17       OP017
17            18       OP018
18            19       OP019
19            20       OP020
20            21       OP021
21            22       OP022
22            23       OP023
23            24       OP024
24            25       OP025
25            26       OP026
26            27       OP027
27            28       OP028
28            29       OP029
29            30       OP030
30            31       OP031
31            32       OP032
32            33       OP033
33            34       OP034
34            35       OP035
35            36       OP036
36            37       OP037
37            38       OP038
38            39       OP039
39            40       OP040

#### 5- Dim_Product

In [620]:
dim_product = smart_factory[["product_id"]].drop_duplicates().sort_values("product_id").reset_index(drop=True)
dim_product.insert(0, "product_key", dim_product.index + 1)
dim_product

   product_key product_id
0            1        P_A
1            2        P_B
2            3        P_C
3            4        P_D
4            5        P_E

#### 6- Dim_Downtime_Reason

In [621]:
dim_downtime_reason = smart_factory[["downtime_reason"]].drop_duplicates().sort_values("downtime_reason").reset_index(drop=True)
dim_downtime_reason.insert(0, "downtime_reason_key", dim_downtime_reason.index + 1)
dim_downtime_reason

   downtime_reason_key    downtime_reason
0                    1          Breakdown
1                    2        Maintenance
2                    3  Material Shortage
3                    4        No Downtime
4                    5              Setup
5                    6        Unspecified

#### 7- Dim_Defect_Type

In [622]:
dim_defect_type = smart_factory[["defect_type"]].drop_duplicates().sort_values("defect_type").reset_index(drop=True)
dim_defect_type.insert(0, "defect_type_key", dim_defect_type.index + 1)
dim_defect_type

   defect_type_key      defect_type
0                1            Crack
1                2  Dimension Error
2                3          Scratch
3                4   Surface Defect

#### 8- Dim_Quality

In [623]:
dim_quality = smart_factory[["type","product_quality"]].drop_duplicates().sort_values("type").reset_index(drop=True)
dim_quality.insert(0, "quality_key", dim_quality.index + 1)
dim_quality

   quality_key type product_quality
0            1    H            High
1            2    L             Low
2            3    M          Medium

#### 9-Fact_Table

In [624]:
smart_factory.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 0 to 10029
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   date                   10000 non-null  datetime64[ns]
 1   shift                  10000 non-null  object
 2   machine_id             10000 non-null  object
 3   operator_id            10000 non-null  object
 4   product_id             10000 non-null  object
 5   planned_time_min       10000 non-null  int64
 6   downtime_min           10000 non-null  int64
 7   downtime_reason        10000 non-null  object
 8   total_units            10000 non-null  int64
 9   good_units             10000 non-null  int64
 10  reject_units           10000 non-null  int64
 11  defect_type            10000 non-null  object
 12  energy_kwh             10000 non-null  float64
 13  type                   10000 non-null  object
 14  air_temperature_k      10000 non-null  float64
 15  process_temperature_k  10000 non-null  float64
 16  rotational_speed_rpm   10000 non-null  int64
 17  torque_nm              10000 non-null  float64
 18  tool_wear_min          10000 non-null  int64
 19  machine_failure        10000 non-null  int64
 20  shift_name             10000 non-null  object
 21  product_quality        10000 non-null  object
dtypes: datetime64[ns](1), float64(4), int64(8), object(9)
memory usage: 1.8+ MB

In [625]:
fact = smart_factory.copy().reset_index(drop=True)
fact["date_key"] = fact["date"].dt.strftime("%Y%m%d").astype(int)
fact = (fact
    .merge(dim_shift[["shift_key", "shift"]], left_on="shift", right_on="shift", how="left")\
    .merge(dim_quality[["quality_key", "type"]], left_on="type", right_on="type", how="left")\
    .merge(dim_downtime_reason, on="downtime_reason", how="left")\
    .merge(dim_defect_type, on="defect_type", how="left"))\
    .merge(dim_machine,on="machine_id", how="left") \
    .merge(dim_operator,on="operator_id", how="left") \
    .merge(dim_product,on="product_id", how="left") \
    .drop(columns=["date","shift","machine_id","operator_id","product_id","downtime_reason","defect_type","type","product_quality","shift_name"])
fact.head()

,planned_time_min,downtime_min,total_units,good_units,reject_units,energy_kwh,air_temperature_k,process_temperature_k,rotational_speed_rpm,torque_nm,tool_wear_min,machine_failure,date_key,shift_key,quality_key,downtime_reason_key,defect_type_key,machine_key,operator_key,product_key
0,480,0,585,552,33,50.99,299.7,309.2,1456,40.6,182,0,20250101,1,1,4,3,1,18,4
1,480,30,683,647,36,61.27,297.7,309.7,1440,51.1,191,0,20250101,1,1,5,2,2,12,2
2,480,39,650,616,34,40.69,300.3,311.7,1707,33.6,158,0,20250101,1,2,5,4,3,29,2
3,480,170,467,394,73,41.49,300.5,309.9,1397,45.9,210,1,20250101,1,1,1,3,4,31,2
4,480,0,740,712,28,42.45,297.4,308.3,1535,34.6,51,0,20250101,1,3,4,2,5,33,5

<div style="color: Green;  padding: 7px; border-radius: 5px; font-weight: bold; font-size: 25px;"> Exploratory Data Analysis </div>